-- Changes in defines.lua for the Byzantium mod

NDefines.NCountry.CORRUPTION_FROM_BANNERS = -0.1
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 10
NDefines.NCountry.PS_FACTION_BOOST = 1
NDefines.NCountry.ENFORCE_CULTURE_TAX_MULTIPLIER = 0.20

NDefines.NMilitary.COSSACKS_SHOCK_DAMAGE_BONUS = 0.25
NDefines.NMilitary.COSSACKS_DISCIPLINE_BONUS = 0.5
NDefines.NMilitary.COSSACKS_MANPOWER_USAGE = 0.00
NDefines.NMilitary.COSSACKS_REINFORCE_SPEED = 10.0
NDefines.NMilitary.COSSACKS_MAINTENANCE_COST = 0.0
NDefines.NMilitary.COSSACKS_USES_CONSTRUCTION = 0.0
NDefines.NMilitary.STRELTSY_FIRE_DAMAGE_BONUS = 0.25
NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = -0.5
NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = 0.5
NDefines.NMilitary.BANNER_MANPOWER_USAGE = 0.00
NDefines.NMilitary.BANNER_REINFORCE_SPEED = 10.0
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 0.0
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 1.50
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 10.0
NDefines.NMilitary.TERCIO_USES_CONSTRUCTION = 0.0
NDefines.NMilitary.TERCIO_DISCIPLINE_BONUS = 0.5
NDefines.NMilitary.TERCIO_MANPOWER_USAGE = 0.00
NDefines.NMilitary.TERCIO_REINFORCE_SPEED = 10.0
NDefines.NMilitary.TERCIO_MAINTENANCE_COST = 0.0
NDefines.NMilitary.TERCIO_AGE_MULTIPLIER = 1.50
NDefines.NMilitary.TERCIO_STARTING_STRENGTH = 10.0
NDefines.NMilitary.TERCIO_FIRE_DAMAGE_BONUS = 0.33
NDefines.NMilitary.TERCIO_FIRE_DAMAGE_TAKEN = -0.33
NDefines.NMilitary.TERCIO_SHOCK_DAMAGE_BONUS = 0.33
NDefines.NMilitary.TERCIO_SHOCK_DAMAGE_TAKEN = -0.33
NDefines.NMilitary.TERCIO_INFANTRY_FIRE = 1.0
NDefines.NMilitary.TERCIO_INFANTRY_SHOCK = 1.0

NDefines.NMilitary.MAN_OF_WAR_USES_CONSTRUCTION = 0.0
NDefines.NMilitary.GALLEASS_USES_CONSTRUCTION = 0.0
NDefines.NMilitary.VOC_INDIAMEN_USES_CONSTRUCTION = 0.0



NDefines.NGovernment.SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 16
NDefines.NGovernment.RUSSIAN_ABILITY_COST = 100
NDefines.NGovernment.RUSSIAN_ABILITY_POOL_SIZE = 300
NDefines.NGovernment.RUSSIAN_ABILITY_BASE_GAIN = 25
NDefines.NGovernment.RUSSIAN_ABILITY_SUDEBNIK_MIN_AUTONOMY = 10
NDefines.NGovernment.RUSSIAN_ABILITY_SUDEBNIK_AUTONOMY_CHANGE = -25
NDefines.NGovernment.RUSSIAN_ABILITY_OPRICHNINA_THRESHOLD = 0.3
NDefines.NGovernment.RUSSIAN_ABILITY_OPRICHNINA_CHANGE = -0.5
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_WE_CHANGE = -5
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.30
