-- Changes in defines.lua for the Byzantium mod

NDefines.NCountry.CORRUPTION_FROM_BANNERS = -0.1
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 10
NDefines.NCountry.PS_FACTION_BOOST = 1

--NDefines.NMilitary.COSSACKS_SHOCK_DAMAGE_BONUS = 0.25
--NDefines.NMilitary.STRELTSY_FIRE_DAMAGE_BONUS = 0.25
--NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = -0.5
--NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = 0.5
--NDefines.NMilitary.BANNER_MANPOWER_USAGE = 0.00
--NDefines.NMilitary.BANNER_REINFORCE_SPEED = 10.0
--NDefines.NMilitary.BANNER_MAINTENANCE_COST = 0.0
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 1.50
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 10.0

NDefines.NGovernment.SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 16
NDefines.NGovernment.RUSSIAN_ABILITY_COST = 100
NDefines.NGovernment.RUSSIAN_ABILITY_POOL_SIZE = 300
NDefines.NGovernment.RUSSIAN_ABILITY_BASE_GAIN = 25
NDefines.NGovernment.RUSSIAN_ABILITY_SUDEBNIK_MIN_AUTONOMY = 10
NDefines.NGovernment.RUSSIAN_ABILITY_SUDEBNIK_AUTONOMY_CHANGE = -25
NDefines.NGovernment.RUSSIAN_ABILITY_OPRICHNINA_THRESHOLD = 0.3
NDefines.NGovernment.RUSSIAN_ABILITY_OPRICHNINA_CHANGE = -0.5
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_WE_CHANGE = -5
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.3

